### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by anjugopinath** [facebookresearch/InterHand2.6M#58]
![image](https://user-images.githubusercontent.com/4654298/119397390-0cc7a100-bca4-11eb-9387-e3f6a72afc46.png)
**I get this warning** 
/s/red/a/nobackup/vision/anju/interhand_venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py:474: UserWarning: This DataLoader will create 40 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
**and soon after, get this message:**
RuntimeError: CUDA out of memory. Tried to allocate 1.31 GiB (GPU 0; 11.78 GiB total capacity; 9.49 GiB already allocated; 678.00 MiB free; 9.80 GiB reserved in total by PyTorch)

**Please see attached image**

**Comment by mks0601** [comment]
follow the message to reduce the gpu memory usage

**Comment by anjugopinath** [comment]
In config.py under 'main' folder, I tried values of 12 and 6 for num_thread (it was earlier 40)..
I don't get the warning anymore. But, I still get "CUDA out of memory' error.

Could you give some suggestions please?

**Comment by mks0601** [comment]
reduce train_batch_size

**Comment by anjugopinath** [comment]
I reduced train_batch_size to 8 and then to 4 and now, it's working. Thank You so much!!

**Comment by anjugopinath** [comment]
I think the problem was that I tried to load all the input images at once (python train.py --gpu 0 --annot_subset all)
I tried with only one subset and it worked with 40 threads and train batch size 16 (config.py)
python train.py --gpu 0 --annot_subset human_annot

**Comment by mks0601** [comment]
Data loading takes the main memory (RAM), not the GPU memory (VRAM). Anyway, good for you to find the solution!
